version: '3.8'

services:
  api:
    build: .
    container_name: bgreport_api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=supersecret-voce-deve-mudar-isso-em-producao
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    restart: unless-stopped
